### ISSUE TITLE
Unsupported HTML block: <html>

### ISSUE THREAD

**Issue by a-a-k** [wescpy/md2googleslides#1]
What's wrong here? How to proceed with html file?

```
Unable to generate slides: Error: Unsupported HTML block: <html>
<head>
<title>title</title>
<style>
@page { size: A4 landscape; margin: 1cm; }
body { font-family: sans-serif; }
h1, h2 { text-align: center; font-size: 32px; } 
.slide { page-break-before: always; margin-bottom: 20px; padding: 20px; border: 1px solid #ccc; }
.slide h2 { text-align: center; font-size: 28px; } 
.slide ul, .slide p { text-align: left; font-size: 20px; } 
.placeholder { background-color: #eee; padding: 10px; text-align: center; float: right; } 
</style>
</head>
<body>

    at fullTokenRules.html_block (C:\Users\aakra\AppData\Roaming\npm\node_modules\@wescpy\md2gslides\lib\parser\extract_slides.js:395:11)
    at processMarkdownToken (C:\Users\aakra\AppData\Roaming\npm\node_modules\@wescpy\md2gslides\lib\parser\extract_slides.js:74:5)
    at C:\Users\aakra\AppData\Roaming\npm\node_modules\@wescpy\md2gslides\lib\parser\extract_slides.js:86:5
    at Array.forEach (<anonymous>)
    at processTokens (C:\Users\aakra\AppData\Roaming\npm\node_modules\@wescpy\md2gslides\lib\parser\extract_slides.js:81:10)
    at extractSlides (C:\Users\aakra\AppData\Roaming\npm\node_modules\@wescpy\md2gslides\lib\parser\extract_slides.js:603:3)
    at SlideGenerator.generateFromMarkdown (C:\Users\aakra\AppData\Roaming\npm\node_modules\@wescpy\md2gslides\lib\slide_generator.js:154:47)
    at generateSlides (C:\Users\aakra\AppData\Roaming\npm\node_modules\@wescpy\md2gslides\bin\md2gslides.js:213:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Herambhbiraris** [comment]
The error you're encountering indicates that the `md2gslides` tool doesn't support HTML blocks in your Markdown file. To resolve this, you should remove the HTML content and instead use pure Markdown to format your slides.

# Title

## Slide 1
- Item 1
- Item 2
- Item 3

## Slide 2
### Subheading
Some text content here.

- Item A
- Item B
- Item C

## Slide 3

or else make it a whole html file using di ul and all.

**Comment by Herambhbiraris** [comment]
The error you're encountering indicates that the `md2gslides` tool doesn't support HTML blocks in your Markdown file. To resolve this, you should remove the HTML content and instead use pure Markdown to format your slides.

"# Title

## Slide 1
- Item 1
- Item 2
- Item 3

## Slide 2
### Subheading
Some text content here.

- Item A
- Item B
- Item C

## Slide 3"

or else make it a whole html file using di ul and all.
